apiVersion: v1
kind: PersistentVolume
metadata:
  name: blob-pv-static
  labels:
    type: azureblob # PVC와 연결하기 위한 라벨
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: azure-blob-static 
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: blob-vol-${PV_STORAGE_ACCOUNT_NAME}-${PV_CONTAINER_NAME}
    volumeAttributes:
      resourceGroup: ${RESOURCE_GROUP_NAME}
      storageAccountName: ${PV_STORAGE_ACCOUNT_NAME}
      containerName: ${PV_CONTAINER_NAME}
    nodeStageSecretRef:
      name: azure-blob-secret 
      namespace: default      